### ISSUE TITLE
Can't Export because of Unicode in journal

### ISSUE THREAD

**Issue by 1j01** [captbaritone/markdown.today#25]
I use emoji occasionally, but also, like...

1:28 PM 
```
C:\Users\Isaiah>pyborgeous -cm unicode -t a
ી𐅎𬙻𬉪𧿻𘂡䪹𡑻𪓃荟𤓞搵荲𩏤䓦◜啬𡯑㐩𫖮𠐯ⓖﶌ췼䬩𣖶𤙱≀𨌐햋炆𣝼᥉㓸₪𧲺𡙡𒍙𠾦𥶰𩱳亜𑂍㪱ἢ챊𧁋⬟𩸳𖧳𘀵֮ഉ牞ྦྷ呱쾑蜏履𧝜𨼆탱𧘾ꮎ𧒮𤏲𥊻⒈𓆊𣮟𪉆𧛫ｸ𠧢𫒕𝁨𑚝ㄭ璼𦶖𧛂증叞㑯𣈲㠃Ꙙ㿦𡁚𠪑ྒ𗻮𗁭𐘖𔔢𠧔垆檖읓𗿾ⳙ뵋𦵀悋𗂜䢙𥳄𠜆🍛ꥄ𤏃寡閑ᴺ葡𫙶鄬쿥ᥚ䝆𧨊𥖴ދ趠𗳋࡙㧍𨍀𫞏𑜇Σ﹏𗠰𢊊𫌵𥩕刨ꛑ𫻢𑌮围𒂤䮦슻𥨠剉𨌏𗗰𖦌怒𥺧𑢧𦕭𢄰儉𫩘䉟𣮣翜睮狯𢁦𠷓𬷘ᖴ🛍𓂆䝯𝃅뵊茈銺㲁궅쒯𠀼荒𩑂繮쬙縒𠾐៍🢄쀾𘐾᧯𦝀ಷ𡭏𪝺（𢹽𧒨𨳿𢐮𨀕𤚪ⷔᏠ𦖾㑘𪞕䴓쬮䭰𨴘찲䲸퇽𤈷씨𧮠䗨婹瞎𝚽〈萑𘖏𩱍⾭⑺𠉬𞤱郴ꍢ𔘵𦆿ᒱ𠡍𬐕𫛖𘄰鍷𐬥껯𐅩𡮷볐𩠑朦𒍋𩶌炳鏞𪈮𫣹𠉣퓊𧸋𪗶꣪𗥁𖽨𨷨𗊺叓𠧳𥐷𣽿쾒俭🆕鋦𦄚ﾸ𫢺戳𠢑𡤄秱𢰨礎巠𨛝㹑𘄧𪳇𥤮𣷟䚦𢤔ꪹ𠧭屰劅𞠋𝇌䶔𠒷𗏊莿𢭈褪㺤덀ꯥ𐡋콻𤝜㛬🍇𡽶၁⠌ꅇ𬁇喕靐像軇𩅴媴㬺𫞐𫈫⍔𗻌뤉𠾮戭𐕟𣅠𐲰𦄈옃큰𛰖䒐圍𑍳𧝕𬃡𗝈䔤ǎ𦘴𒉭嫏ꉵ𦃀ᇸ囤𝅒𐰷藅𫁉🐹𗲠𖨚𧏖𬍦𧧗𩙻𡋚𗲫𨊪𪖜𫟙濮𬏒𢛗𢿀ꏂ⢾묬𦆜𡡄欙𐛠矫捣🌝𩎋菭𪳤𢛥𠍦寶精⁰䭓𢽪𣎷💊𘀫⧰䓉𐔳𨣴𪨽𘜴𠗄𒎖먜𦯫⺎텦굤𢤒탈𥻾줌긴𫩌𠄈⻃𪘁𔗬𗱩봝⧇燆𧴚𖢷㹚𦇧♵ꝳڮ䓅𬔀𥔰𗎅㫦𩇨𣸠𥶵ៈ𦥩𤙺㠉𗞢𠦢𨢘𫗅冷𒃥𡻸𩥐𣎇𠙜𬨕𬭫깭𪹚攚̤蕷𣍃𖩌𥮯骟󠅀泥𦅅𠽚𐦠魃𗮬墙릺𧃝𦭳𡩲𦶳𖼷駚𦊩𠞟劕𝦰𨹖柌𩐗篠𩧹𦟢퇋ᛕ剹𓎻𡠼➓멕𓉐𡊄𥀗𩎋才ⴲ𥻫쑐뽘虧𬵐𩻳𐒶𔔣곙𐡁㺋𪳽𗎙즈𧯕➱𓅂𠰺𘡚𢳳𨑝𨹮𪏀𦟹𥵤焹𩲖쁣𤦵恅状𡌭𨂴𞠎ํ𝄛𫚈דᢥぴ𥥆𢟨𩘤𗔼뀝粻⮸𩂁𠇹𦍃𠘞𧅝ⶺ𥅉𐂻鶴𗅹𩅅𖦙𨽖Դ𦶁쑥ڑ㌿䴛𥒠𨖙ثᶦ滻𩻸䊠飛𘚚𧭢𫣃𤮔暟𠵚𥫺쩪𪝹鞯𥋋𐡿𤂡𡼿枹뭠𑣔𥪸𠜒뼡ᬂ礗𦲬𬌲𘄭ꛇ𗄟𣮳햒𖭯𣘕㗓𪨴蛦틎𣃜㍆𤝔𗼷︼𬠷踈ꄯ粱癇♐⒯媩🡫𝀷𫍆ዯꍻ𫢞㪰뫡𡡃𦭿↕溶🐢檺𬅆괁𪵑≩𘜎𥇢𬫚𒃏𤉫𠞙㹕틠𤝊圳矢ꥶ𬩏🈘𡁉劮𬤈∓ꆓ𦃮𥧭𩞲𡲡𣋆🜐靜🙬몏絒筍ঈ𢍱𦁤哤𢳖𫃧𨦗ꐬ砏䶉𫇱韮𥉸੫𘓸𫷀𩳮ܭ𩲤𗪞ɽ𩏇𗊙欗𗵥𗏈ꃸ𫎸𣎜𨏬𐒡𢟄幵㦮𐎅鱡𪞿薻𖨲𡥅𬴫𘡈𝨂븇ɀ숵𡢼𩲛𨗲𢪵𪔂𖥂ꔣ𡮊圈屮슁𑒐羙𧞩𪸓𥍗늑𥉻춟𑋆𬏃❛鐁𪼝쩥𤏰𬁭鸜譲쑑롎傶𠯊坆辧𘔌绝襦𡭟먹𬄑𘁵휮𡳽譯𠟞𦒷𥫗祵롨𗅳㧄𧢫踹딊腖𠳪𥶘Зᇪ쉃𧽥勵𠔼𖣜🖯吋𦏤嘤𣔎艞䘵𡌦𢆒𝞁𩈩𫇏𧻖ꄠ心𘡓ᤂ醟𪸢🄕𢐏삼唂렚𡩌𡿒𬂒⥃㼘줧𤆉𢘫𠵱𣄎𝢉⌥𦿾𐹼𪡯𬒳嚃㤡ܬ㹒鐕𢉍硎🎿𫰄𩟂虧Ẽ𤈯𬷱敉𐨺쎨𘛒𦊄𝀔✰𢱙𢛬𡊞𗻠𐚀𤭥⨔𖬻𠤷깨𣥨𥉥𠜿Ꮅ𫱀틀䌷𑋋𧥵婀𢋎𨻎㦺當𥻠嶝🀱𠲫𦛭𗯾𫓏𫭒陵𝝵𞢏𫮷𦄅𠁅𡃟𖽖ᮣ𓇚𢹌澊𐭸뙣𢟖껑𝠇딍𘅫𩿉뎥注𫮇𤌙뼮箖쁟犥𪃤𧜮𗁓齬텫𤑔𦽩ᱴ𧓹𧔉Ɥ𣓅ꂖ𨩈🎿䠦𢺻𩛛𪾛𨾌䇓炾팞𢻩𐫌𤐬屈⟾峿摨토𦵎𤵽弅梛𧡏𝞜𨴻魊镆𗔉뜴𔔧𨂬浲䮰ꪣ𑃧𨑫ᑟ𠣹𖥭皋㧩쑟𢽃𬦾𝢔𬝎𠉉𠛪䴗𝕞𪨦𢎝𣫇𥄒𧛓잓䆁픥𣺷𪊥ꠙ玠𩮀𦭡옳𦂍𐘆𡂻𥆫𦃶穼花귫𡍩𬶴𩓱𦺴𦴶𪂢፮𑇤𦈠𣽗Ḟ𫠬𡧈疛𐮜鶯蝆𦌝𡡐q𤚼𧐑䪰𪾎𠐙𘈔舙𗎅热𐘊倿Ṗᚏ뇿𤟿𢾁襙𫢯𓀣𤫣𩧫𧁜鰤𥻛𢓀𬪖𣺥𪀘ꫮ𧁉𢢣𨛋㤢𤛥𤷖𬋒𐏂𩂧𑋲覟波𦶋𨚦𥦈𢍃慶앉匴⬭𧄖𐕛𦭿𩫁꼥堕𥉊“樝ᇗ𘞈皶👭𨱺𤲐𥫝𦛩辢ⲋ쪡𫇞𪰛𢁖뽻㠨ꗥැ𨸇ᠱ𐌠ﯟ呼𩑶Ⲧ𠃇ힸ𪯦뫦𐧾𒅺缲𢑆撰𨶵𢟋𪤪🝋ɏ𩉃𢸁絣悁🟃趸𦅧𨵋𪩓㪰𘜁𫛗뮤ࢨ䊪內憯𧽘𨒱𗪘𡡁𡕢𡃊𧁬䌗𫅊ៈ𠺜ꧽ뾪逊䠷𬵙㜷𣷌𧶛ꡭ𝢋Ș𩛆𤾻Ɯ𫑔穑女𗾀𧰞𬬤𗯿ﰂᦍ㒆⡬픉𠾻𥲀𨧺ޅ𒄺蓲㡃⯑𠣎⑱𝓡𠪱䞼짮𣕸𥚵먵𫺵堜戻볏𨺍܈鋶𫦹䴁瘋ꐃ죰넝𪸥𢵠⸺揅𥑚ᜐ孽𩄐ѳ𩌷⨰䯻뢿ក𪲸🅰𧮡Ⴭ鎞𦸣𩗺𡍍𨙰벧姺ॆ𒅅𡞮ꂡꔕ𧄿돇챜𣉑𨶶퉁𣗭ݮ𧜝𤶮虈敨𩢸𧮶𥧿䵭ᙍ正녰没𧙢s𠦉𩼉𪃭𨵞ᡣ🙠맫𐐫𨛮𧔭𨗯𠐚䓖𢡑𡤋𠎥꿹𠲘纹쏩𡠹 杛𥻃𥏣矝𡚬믽𪑪𡃄𤧞𫢷𦥯𫉨𥎱𗮒𡉱𣶢䘄脭𘥸𗀿𖼔𦬌ࡄ耮𥇂휈療籁𪿓𣇻𣑦𣓄𩕋翗恸Ṿ𥣆댧🌉𢰳𠴶뎾𧟮𬃩𫮬𓁗𤅛𗣶硒𨸠𡪯睗釋𨳉𫇜𫢠襪ย위ዴ퉾𣀋𠉠𗮂햰㤓𢙅奄𧩴⣷𑈃𗋑𘣽𘐭𝛈틵𑜸噾𘞶𫊬歚𡪀𠓤ޣ𝂴𫦳𡻦𠔼⺰𪿜䬳⿐𨕤蟂𣺊𧀙㶞ᬎ⫒뾹𤴒𩮩𬌼齥𤕂𫂴𫰔𥭨虑ㆺ倳𗰶𡓶𢘏𫮥㒷씋𢱠든𫳣𩁋쬠 洿🞌𪩄묛𪾻㭖靾ⴰ𬔇ᮩ⟡𥾺𤰢ㄣ㬣᳟𗔏뤍은𨴻瓂𦁩䯕營𝛨𢆇덾𨆉𥦳𠾣𠭕𬞷𠊟䣲𡅳𧔹𧂢𘦒蕒𥧢𠎤㎼媊𥒧泾𣨡𦥀𦉱㨥𡔑㳷𣇇𤴄𐐰𨩲𥴺𧩩𬦷풘𗖈琺댦証󠇌𪒔់㯳쯵繷闓℄쳨𡍌乜𒉸稍𨼌Č쯝犠𫌓ﾋ𬮲笏劳𫧇鵧Y쏏𪽫𢦙곚𦋏𥯆💿뷋爦𫣚֬⣪쭶컖跶㨱ኮ𑄻ᢗ𤑫𫻂𢱩㠘𠰒챚퀔躕𒐖ꑷ𨋽𧳂𝢯𪰪𡓯㋕쨀𪝍𣝍𐌛禖𪝉𨌄🏦뚂  0       2       16      65
```

2:54 PM  
؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁؁
𒐪𒐪𒐪𒐪𒐩𒐪𒐪𒐪𒐪𒐪𒐫
𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥vvvvvv𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥𪚥

lol 😅

---

It gets this when I try to export:
```
Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at t.getAsDataURI (https://markdown.today/static/js/main.2ebbbfa0.js:4:6452)
    at https://markdown.today/static/js/main.2ebbbfa0.js:12:31526
    at https://markdown.today/static/js/main.2ebbbfa0.js:30:2733
    at Object.onTouchTap (https://markdown.today/static/js/main.2ebbbfa0.js:30:3494)
```

There are some workarounds identified here: https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem
But exporting a `Blob` with `createObjectURL` might be easier.

**Comment by captbaritone** [comment]
Hey! Somehow I missed this. Thanks for reporting.
